---
- hosts: flask
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
        state: present

    - name: Copy Flask app code
      copy:
        src: ../app/    # Your repo path on GitHub Actions runner
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: '0755'


    - name: Install app requirements
      pip:
        requirements: /home/ubuntu/app/requirements.txt
        executable: pip3

    - name: Copy systemd service file
      copy:
        src: files/app.service
        dest: /etc/systemd/system/app.service
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start Flask app
      systemd:
        name: app
        state: started
        enabled: true

    - name: Configure NGINX reverse proxy
      copy:
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:5000;
              }
          }
        dest: /etc/nginx/sites-available/default

    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted
